# Site settings
title: JS CV
description: JS Curriculum Vitae
# baseurl: "" # the subpath of your site, e.g. /blog
url: tkxkd0159.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jaeseung Lee
user_description: Dynamic Software Engineer with 5 years of experience building scalable, high-performance systems and optimizing data infrastructure. While specialized in Go, Rust, and Kubernetes, I quickly adapt to new technologies and am eager to leverage Java and other languages as needed. Experienced in leading teams to deliver resilient cloud platforms and secure blockchain platform, with a strong focus on automation, performance, and continuous improvement to solve complex business challenges.
user_title: Software Engineer
email: tkxkd0159@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: [package.json, src, node_modules, vendor]
